server:
  port: 8501

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://59.110.150.184:3307/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  data:
    redis:
      host: 59.110.150.184
      port: 6380

mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml

# 自定义配置
spzx:
  minio:
    endpointUrl: http://127.0.0.1:9000
    accessKey: minioadmin
    secureKey: minioadmin
    bucketName: spzx-bucket
  auth:
    noAuthUrls:
      - /admin/system/index/generateValidateCode
      - /admin/system/index/login