server:
  port: 8701

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:33306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: yzc13569291231

  data:
    redis:
      host: localhost
      port: 6380

mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml

# 自定义配置
spzx:
  minio:
    endpointUrl: http://127.0.0.1:9000
    accessKey: minioadmin
    secureKey: minioadmin
    bucketName: spzx-bucket
  auth:
    noAuthUrls:
      - /admin/system/index/generateValidateCode
      - /admin/system/index/login